CONTIKI_PROJECT = mqtt
all: $(CONTIKI_PROJECT)

MODULES += os/net/ipv6 os/net/routing os/net/app-layer/coap os/net/app-layer/mqtt
MODULES_REL += ./resources

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
